name = "Hugo Blog Extended"
license = "MIT"
licenselink = "https://github.com/BiosPlus/hugo-blog-extended/blob/main/LICENSE"
description = "A fork of HBA with features that deviate from the original theme, such as a new layout, colors, and more."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/BiosPlus/hugo-blog-extended/"

# If you have a running demo of the theme.
demosite = "https://hugo-blog-extended.pages.dev/"

tags = ["blog", "responsive", "minimal", "dark", "light", "multilingual"]
features = ["blog", "sass", "dark"]

min_version = "0.147.8"

# If the theme has a single author
[author]
    name = "BiosPlus"
    homepage = "https://github.com/BiosPlus"
